import type {
  Activity,
  BudgetGroup,
  DrawSession,
  Pair,
  PairMember,
  ScheduledSession,
  SessionOutcome,
  WeeklyActivityBan,
} from './types';

export const pair: Pair = {
  id: 'pair-001',
  name: 'G + L',
  timezone: 'Australia/Melbourne',
  created_at: '2026-06-01T00:00:00.000Z',
};

export const members: PairMember[] = [
  {
    id: 'member-g',
    pair_id: pair.id,
    display_name: 'G',
    color: '#f97362',
    created_at: '2026-06-01T00:00:00.000Z',
  },
  {
    id: 'member-l',
    pair_id: pair.id,
    display_name: 'L',
    color: '#7ad7bd',
    created_at: '2026-06-01T00:00:00.000Z',
  },
];

export const budgetGroups: BudgetGroup[] = [
  {
    id: 'budget-tiny',
    pair_id: pair.id,
    name: '小花费',
    amount_hint: '$',
    sort_order: 1,
  },
  {
    id: 'budget-treat',
    pair_id: pair.id,
    name: '小犒劳',
    amount_hint: '$$',
    sort_order: 2,
  },
  {
    id: 'budget-splurge',
    pair_id: pair.id,
    name: '认真宠',
    amount_hint: '$$$',
    sort_order: 3,
  },
];

export const activities: Activity[] = [
  {
    id: 'activity-night-market',
    pair_id: pair.id,
    title: '夜市小吃巡游',
    note: '挑三家摊位，每样都分着吃。',
    budget_group_id: 'budget-treat',
    duration_minutes: 120,
    tags: ['吃的', '出门'],
    created_by_member_id: 'member-g',
    status: 'active',
    created_at: '2026-06-02T00:00:00.000Z',
  },
  {
    id: 'activity-home-ramen',
    pair_id: pair.id,
    title: '在家升级拉面',
    note: '溏心蛋、配菜和没试过的新汤底。',
    budget_group_id: 'budget-tiny',
    duration_minutes: 75,
    tags: ['在家', '吃的'],
    created_by_member_id: 'member-l',
    status: 'active',
    created_at: '2026-06-03T00:00:00.000Z',
  },
  {
    id: 'activity-pottery',
    pair_id: pair.id,
    title: '陶艺体验课',
    note: '如果抽到它，就提前预约。',
    budget_group_id: 'budget-splurge',
    duration_minutes: 150,
    tags: ['动手', '需预约'],
    created_by_member_id: 'member-g',
    status: 'active',
    created_at: '2026-06-04T00:00:00.000Z',
  },
  {
    id: 'activity-sunrise',
    pair_id: pair.id,
    title: '日出面包散步',
    note: '早起走走，买个面包，趁世界还安静回家。',
    budget_group_id: 'budget-tiny',
    duration_minutes: 90,
    tags: ['早晨', '出门'],
    created_by_member_id: 'member-l',
    status: 'active',
    created_at: '2026-06-05T00:00:00.000Z',
  },
  {
    id: 'activity-arcade',
    pair_id: pair.id,
    title: '街机对决夜',
    note: '一人十个币，赢家决定甜品。',
    budget_group_id: 'budget-treat',
    duration_minutes: 105,
    tags: ['游戏', '室内'],
    created_by_member_id: 'member-g',
    status: 'active',
    created_at: '2026-06-07T00:00:00.000Z',
  },
  {
    id: 'activity-bookshop',
    pair_id: pair.id,
    title: '书店互选',
    note: '给对方挑一本小书。',
    budget_group_id: 'budget-tiny',
    duration_minutes: 60,
    tags: ['安静', '室内'],
    created_by_member_id: 'member-l',
    status: 'active',
    created_at: '2026-06-08T00:00:00.000Z',
  },
  {
    id: 'activity-karaoke',
    pair_id: pair.id,
    title: 'K 歌小房间',
    note: '先暂停，留给下一个下雨周。',
    budget_group_id: 'budget-treat',
    duration_minutes: 120,
    tags: ['音乐', '室内'],
    created_by_member_id: 'member-g',
    status: 'paused',
    created_at: '2026-06-06T00:00:00.000Z',
  },
];

export const drawSessions: DrawSession[] = [
  {
    id: 'draw-seed',
    pair_id: pair.id,
    target_week_start_date: '2026-07-06',
    created_by_member_id: 'member-g',
    status: 'idle',
    created_at: '2026-06-29T00:00:00.000Z',
  },
];

export const weeklyActivityBans: WeeklyActivityBan[] = [
  {
    id: 'ban-seed-g-karaoke',
    pair_id: pair.id,
    draw_session_id: 'draw-seed',
    member_id: 'member-g',
    activity_id: 'activity-karaoke',
    created_at: '2026-06-29T00:00:00.000Z',
  },
];

export const scheduledSessions: ScheduledSession[] = [
  {
    id: 'session-current',
    pair_id: pair.id,
    activity_id: 'activity-night-market',
    draw_session_id: null,
    target_week_start_date: '2026-06-29',
    status: 'ongoing',
    todo_text: '周四前先各自挑想吃的摊位',
    created_at: '2026-06-22T00:00:00.000Z',
  },
  {
    id: 'session-future',
    pair_id: pair.id,
    activity_id: 'activity-home-ramen',
    draw_session_id: null,
    target_week_start_date: '2026-07-06',
    status: 'planning',
    todo_text: '周日买好配菜',
    created_at: '2026-06-23T00:00:00.000Z',
  },
  {
    id: 'session-needs-review',
    pair_id: pair.id,
    activity_id: 'activity-arcade',
    draw_session_id: null,
    target_week_start_date: '2026-06-22',
    status: 'needs_review',
    todo_text: '补一下街机夜到底成没成',
    created_at: '2026-06-17T00:00:00.000Z',
  },
  {
    id: 'session-history',
    pair_id: pair.id,
    activity_id: 'activity-sunrise',
    draw_session_id: null,
    target_week_start_date: '2026-06-22',
    status: 'completed',
    todo_text: '试试杏仁可颂',
    created_at: '2026-06-16T00:00:00.000Z',
  },
  {
    id: 'session-missed',
    pair_id: pair.id,
    activity_id: 'activity-karaoke',
    draw_session_id: null,
    target_week_start_date: '2026-06-15',
    status: 'not_done',
    todo_text: '订两小时',
    created_at: '2026-06-09T00:00:00.000Z',
  },
];

export const sessionOutcomes: SessionOutcome[] = [
  {
    id: 'outcome-history',
    scheduled_session_id: 'session-history',
    outcome_type: 'completed',
    rating: '顶级',
    reason: null,
    replacement_activity_id: null,
    agreed_by_member_ids: [],
    created_at: '2026-06-28T09:00:00.000Z',
  },
  {
    id: 'outcome-missed',
    scheduled_session_id: 'session-missed',
    outcome_type: 'not_done',
    rating: null,
    reason: '下班后两个人都太累了。',
    replacement_activity_id: null,
    agreed_by_member_ids: [],
    created_at: '2026-06-21T09:00:00.000Z',
  },
];
